Refactor NodesUtilizaton for initial sync
G-Research/yunikorn-history-server pull request #283
Opened 2024-10-16 22:05 UTC by sudiptob2

closes #282

based on #271

2024-10-21 14:11 UTC, nikola-jokic requested changes
Looks good! Minor change requested and we can merge this

2024-10-21 14:11 UTC, nikola-jokic commented on internal/webservice/routes.go
>  			Writes([]dao.PartitionNodesUtilDAOInfo{}).
You probably need to update this as well for documentation purposes. It writes `model.NodeUtil` now

2024-10-21 14:35 UTC, nikola-jokic approved these changes
lgtm

2024-10-29 19:11 UTC, sudiptob2 commented
Dropped node utilization in #305

2024-10-29 19:11 UTC, closed without merging